# Generated by Django 3.2.4 on 2021-07-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_booktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='book_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.booklink'),
        ),
    ]
