# Generated by Django 3.2.4 on 2021-07-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210707_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='book_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
