# Generated by Django 3.2.4 on 2021-07-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_booktype_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktype',
            name='book_title',
        ),
    ]
