# Generated by Django 3.2.4 on 2021-07-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_remove_booktype_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklink',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
