# Generated by Django 3.2.4 on 2021-07-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_booklink_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklink',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
