# Generated by Django 3.2.4 on 2021-07-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_alter_booklink_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklink',
            name='date',
        ),
    ]
